name: Run Postman Tests with Newman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman and HTML Extra Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Run Postman Collection with HTML Report
      run: |
        newman run CapstoneProject.json -e FootballAPI.json -r cli,htmlextra --reporter-htmlextra-export capstoneresults.html
